# Data Collection Configuration
collectors:
  curriculum:
    sources:
      - type: utah_board
        url: "https://www.schools.utah.gov/curr/science"
        update_frequency: "monthly"
      - type: textbooks
        path: "/data/sources/textbooks"
        update_frequency: "quarterly"
  
  classroom_interaction:
    privacy:
      remove_identifiers: true
      encryption_required: true
    retention_period: "5 years"
    
  management_scenarios:
    validation:
      expert_review_required: true
      minimum_reviewers: 2
    
  scenario:
    sources:
      - type: utah_board_education
        url: "https://www.schools.utah.gov/curr/science"
        update_frequency: "monthly"
      - type: expert_submissions
        path: "/data/scenarios/approved"
        review_required: true
    
    validation:
      expert_review_required: true
      minimum_reviewers: 2
      standards_alignment: true
    
    privacy:
      remove_identifiers: true
      encryption_required: true
  
  interaction:
    privacy:
      student_anonymization: true
      teacher_anonymization: "partial"
      encryption_level: "high"
    
    retention:
      duration: "5 years"
      backup_frequency: "daily"
    
    validation:
      quality_check_required: true
      context_preservation: true

processing:
  sanitization:
    remove_names: true
    remove_locations: true
    remove_dates: false
    preserve_context: true
  
  enrichment:
    add_metadata: true
    add_timestamps: true
    add_validation_status: true

storage:
  format: "json"
  encryption: true
  compression: true
  backup:
    frequency: "daily"
    retention: "90 days"
  
validation:
  content_review:
    expert_required: true
    standards_alignment: true
  privacy_check:
    required: true
    automated_scan: true 